# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:47
from __future__ import unicode_literals

from django.db import migrations
import sys
sys.path.insert(0, 'Users/David/documents/bringing_buzzwords_home/')
from data_import import *

county_pop()
geo_pop()
station_pop()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(county_pop(), geo_pop(), station_pop())
    ]
